theme: jekyll-theme-minimal
title: "Michael Schott"
description: "I'm a 3rd year physics graduate student at the University of Arizona with research interests in machine learning and complex systems and their use in computational physics."

    # "This site details all of my current research projects, including progress and current status, as well as some descriptions of previous projects."
