theme: jekyll-theme-minimal
title: "Michael Schott"
description: "This site details all of my current research projects, including progress and current status, as well as some descriptions of previous projects."
